services:
  bot:
    image: epicpt/bot_question:latest
    container_name: bot_question
    depends_on:
      migrate:
        condition: service_completed_successfully
    env_file:
      - .env
    volumes:
      - ./materials:/materials
    network_mode: "service:amneziawg_q"
    restart: always

  migrate:
    image: migrate/migrate
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    command: [ "-path", "/migrations", "-database", "${POSTGRES_URL}", "up" ]
    volumes:
      - ./migrations:/migrations
    networks:
      - app_network_q

  postgres:
    image: postgres:latest
    container_name: postgres_bot_question
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - app_network_q

  amneziawg_q:
   image: docker-amneziawg:local
   container_name: amneziawg_q
   ports:
    - 51820:51820/udp
   cap_add:
    - NET_ADMIN
    - SYS_MODULE
   devices:
    - /dev/net/tun:/dev/net/tun
   environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
   volumes:
    - ./wireguard:/config
   sysctls:
    - net.ipv4.conf.all.src_valid_mark=1
    - net.ipv4.ip_forward=1
   restart: unless-stopped
   networks:
     app_network_q:

networks:
  app_network_q:
    driver: bridge

volumes:
  postgres_data:
